### ISSUE TITLE
Error, with only import

### ISSUE THREAD

**Issue by tktpoto** [AminHP/gym-mtsim#47]
Hello,

I recently discovered this project and was eager to try it out. However, after installing the project using pip, attempting to import it immediately resulted in an error. The error message is as follows:

Traceback (most recent call last):
  File "/mnt/c/Users/franc/Documents/GitHub/GCollab_Lstm_Renforcement/test.py", line 1, in <module>
    from gym_mtsim import OrderType
  File "/home/osdann/.local/lib/python3.10/site-packages/gym_mtsim/__init__.py", line 13, in <module>
    'original_simulator': MtSimulator(symbols_filename=FOREX_DATA_PATH, hedge=True),
  File "/home/osdann/.local/lib/python3.10/site-packages/gym_mtsim/simulator/mt_simulator.py", line 42, in __init__
    if not self.load_symbols(symbols_filename):
  File "/home/osdann/.local/lib/python3.10/site-packages/gym_mtsim/simulator/mt_simulator.py", line 73, in load_symbols
    self.symbols_info, self.symbols_data = pickle.load(file)
  File "/home/osdann/.local/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 2728, in new_block
    return klass(values, ndim=ndim, placement=placement, refs=refs)
TypeError: Argument 'placement' has incorrect type (expected pandas._libs.internals.BlockPlacement, got slice)".

I am using WSL 2 and have set up a new Conda environment specifically for this. 
So far, I have only installed the latest version of mtsim and bs3.

Could there be an issue on my end ? Any help would be greatly appreciated.

Thank you.

**Comment by tktpoto** [comment]
Following the suggestion in this issue: "https://github.com/AminHP/gym-mtsim/issues/44", I installed pandas version 1.5, which resolved the initial problem. However, I encountered a new error related to package dependencies:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gym-mtsim 2.0.0 requires pandas>=2.0.3, but you have pandas 1.5.3 which is incompatible.

It seems there's a conflict between the version of pandas recommended in the issue and the version required by gym-mtsim 2.0.0.
(But in the end, I force the download and it worked)

**Comment by AminHP** [comment]
Hi @tktpoto , could you try installing `pandas==2.0.3` please? It should probably work without raising the second error.

**Comment by samarthshrivas** [comment]
> Hi @tktpoto , could you try installing `pandas==2.0.3` please? It should probably work without raising the second error.

It worked !!!. Thanks.
Maybe you should include this in requirements.txt

**Comment by worthy7** [comment]
Can you upgrade this to support latest version of python?

**Comment by darkrams98** [comment]
**use pandas to see what you have inside pkl file** 

import pickle
import pandas as pd
class DummySymbolInfo:
    def __init__(self, *args, **kwargs):
        pass
    def __setstate__(self, state):
        # state معمولاً یک dict از فیلدهاست
        self.__dict__.update(state)
class FixUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module == 'gym_mtsim.metatrader.symbol' and name == 'SymbolInfo':
            return DummySymbolInfo
        return super().find_class(module, name)
with open('symbols_forex.pkl', 'rb') as f:
    symbols_info, symbols_data = FixUnpickler(f).load()
print("type(symbols_info) =", type(symbols_info))
if isinstance(symbols_info, list):
    for info in symbols_info:
        print(info.__dict__)
elif isinstance(symbols_info, dict):
    for sym, info in symbols_info.items():
        print(sym, "→", info.__dict__)
print("\nsymbols_data keys:", list(symbols_data.keys()))
for sym, df in symbols_data.items():
    print(f"\n--- DataFrame for {sym} ---")
    print(df.info())
    print(df.head())

**then you can convert a csv file to pkl with needed format :** 

import pandas as pd
import pickle
from gym_mtsim.metatrader.symbol import SymbolInfo
df = (
    pd.read_csv(
        'XAU_1h_data.csv',
        sep=';',
        parse_dates=['Date'],
        index_col='Date'
    )
    .sort_index()
    [['Open','High','Low','Close','Volume']]
    .tz_localize('UTC')
)
info = object.__new__(SymbolInfo)  
for attr, val in {
    'name':               'XAUUSD',
    'market':             'Forex',
    'currency_margin':    'XAU',
    'currency_profit':    'USD',
    'currencies':         ('XAU','USD'),
    'trade_contract_size':100000.0,
    'margin_rate':        1.0,
    'volume_min':         0.01,
    'volume_max':         500.0,
    'volume_step':        0.01
}.items():
    setattr(info, attr, val)
symbols_info = {'XAUUSD': info}
symbols_data = {'XAUUSD': df}
with open('symbols_forex_new.pkl', 'wb') as f:
    pickle.dump((symbols_info, symbols_data), f)
print("Done writing symbols_forex_new.pkl")
